### ISSUE TITLE
假龙类成功率低，容易用力过度

### ISSUE THREAD

**Issue by miyouzi** [Mufanc/Genshin-SmartFishingRod#12]
小鱼可以很轻松钓上来，但是假龙类经常用力过度，配置 `progress-threshold` 调成 `0.1` 成功率还是不高

分辨率方面没有 1600x900 
![image](https://user-images.githubusercontent.com/24269465/142237013-26ed388d-1d84-4be2-8d22-2996854a6db4.png)

**Comment by Mufanc** [comment]
添加启动参数可以让游戏强行以 1600x900 启动

**Comment by miyouzi** [comment]
> 添加启动参数可以让游戏强行以 1600x900 启动

我是用源码运行，指的是 `.\main.py -popupwindow` 么，尝试过了，还是容易用力过度

![image](https://user-images.githubusercontent.com/24269465/142245158-313f402a-60a1-4cfc-a901-fad0a486d83b.png)

## 补充动图：

![finishing-hd - 副本](https://user-images.githubusercontent.com/24269465/142247772-81f97912-a7fe-4ef7-9885-6b05221c8e74.png)

**Comment by Mufanc** [comment]
配置 configs.yml 中的 game-executable 项并将游戏交由脚本启动，窗口大小应该就正常了；在窗口不为 1600x900 的时候，脚本的表现会有些奇怪（

**Comment by miyouzi** [comment]
> 配置 configs.yml 中的 game-executable 项并将游戏交由脚本启动，窗口大小应该就正常了；在窗口不为 1600x900 的时候，脚本的表现会有些奇怪（

上图就是这么启动的，钓鲽鱼就很正常，炮鲀也挺正常，就假龙类特别用力，应该不是分辨率的问题，UI的位置都抓对了

配置如下，`game-executable` 一开始就配好了
```yaml
# 游戏可执行文件路径
game-executable: 'D:\Game\Genshin Impact Game\YuanShen.exe'

# 游戏窗口类名和窗口标题
game-window: [ 'UnityWndClass', '原神' ]

# 使用 Alpha 通道的值提高检测准确度，会带来一定性能开销
# [!] 某些旧版显卡可能无法使用此功能，如果适配出现问题请将该项设置为 False 并更换模板
use-alpha: True

# 强制将所有颜色转换为灰色，在 Alpha 模式无法使用时可能按需开启
gray-only: False

# 当游标在滑框内达到此进度后不再点击
progress-threshold: 0.1
```
