### ISSUE TITLE
什么都没改，忽然失效？？？

### ISSUE THREAD

**Issue by cibimo** [Mufanc/Genshin-SmartFishingRod#14]
修改了模板匹配方式后可以正常使用
detector.py
```
result = cv2.matchTemplate(target, template, cv2.TM_CCOEFF_NORMED)
min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)
# similarity = 1 - min_val  # 计算相似度
similarity = max_val
min_loc = max_loc
```

detects.yml
```
templates:
  - name: button
    rect: { left: 0.83, top: 0.88, right: 0.13, bottom: 0.03 }  # 识别区域
    threshold: 0.5
    template: button.png

  - name: hook
    rect: { left: 0.49, top: 0.1, right: 0.49, bottom: 0.76 }
    threshold: 0.5
    template: hook.png
```
